### ISSUE TITLE
Camera View / Gear Wipe

### ISSUE THREAD

**Issue by newgenerationspaceprogram** [Jmaster9999/Sperahead-Gaming-Exile-Issues#3]
The Issue: 
Spawning in on spawn island with a rabbit/bunny style camera view, however, player is invisible.

What causes the issue (known): 
1. Being injured and "hard" logging and come back.
2. Logging out after 5 minutes until restart.

What is affects:
Because of the player's data needing to be wiped to solve his issue. 
He/she will loose EVERYTHING they worked for, including their entire base, pop tabs, locker pop tabs. Everything that is connected to their profile, will be wiped. Because their profile needs to be deleted!

Please offer us to submit support tickets for compensation, because as soon as we figured out it was the number 2 issue, we get slapped with the number 1 issue the second day. The people that daily play Exile are getting SLAPPED because we can't receive compensation. 

Please fix this issue, I suggest copying what they have in their database and pasting it in once they create a new character.

**Comment by Jmaster9999** [comment]
Fixed
